// Mocks generated by Mockito 5.4.6 from annotations
// in tracking_app/test/features/profile/presentation/cubit/profile_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;
import 'package:tracking_app/config/base/base_response.dart' as _i5;
import 'package:tracking_app/features/profile/domain/entities/all_vehicles_response_entity.dart'
    as _i9;
import 'package:tracking_app/features/profile/domain/entities/profile_data_response_entity.dart'
    as _i6;
import 'package:tracking_app/features/profile/domain/repositories/profile_repo.dart'
    as _i2;
import 'package:tracking_app/features/profile/domain/use_cases/get_driver_data_use_case.dart'
    as _i3;
import 'package:tracking_app/features/profile/domain/use_cases/get_vehicles_use_case.dart'
    as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeProfileRepo_0 extends _i1.SmartFake implements _i2.ProfileRepo {
  _FakeProfileRepo_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [GetDriverDataUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetDriverDataUseCase extends _i1.Mock
    implements _i3.GetDriverDataUseCase {
  MockGetDriverDataUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ProfileRepo get profileRepo =>
      (super.noSuchMethod(
            Invocation.getter(#profileRepo),
            returnValue: _FakeProfileRepo_0(
              this,
              Invocation.getter(#profileRepo),
            ),
          )
          as _i2.ProfileRepo);

  @override
  _i4.Future<_i5.BaseResponse<_i6.ProfileDataResponseEntity>> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue:
                _i4.Future<
                  _i5.BaseResponse<_i6.ProfileDataResponseEntity>
                >.value(
                  _i7.dummyValue<
                    _i5.BaseResponse<_i6.ProfileDataResponseEntity>
                  >(this, Invocation.method(#call, [])),
                ),
          )
          as _i4.Future<_i5.BaseResponse<_i6.ProfileDataResponseEntity>>);
}

/// A class which mocks [GetVehiclesUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetVehiclesUseCase extends _i1.Mock
    implements _i8.GetVehiclesUseCase {
  MockGetVehiclesUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ProfileRepo get profileRepo =>
      (super.noSuchMethod(
            Invocation.getter(#profileRepo),
            returnValue: _FakeProfileRepo_0(
              this,
              Invocation.getter(#profileRepo),
            ),
          )
          as _i2.ProfileRepo);

  @override
  _i4.Future<_i5.BaseResponse<_i9.AllVehiclesResponseEntity>> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue:
                _i4.Future<
                  _i5.BaseResponse<_i9.AllVehiclesResponseEntity>
                >.value(
                  _i7.dummyValue<
                    _i5.BaseResponse<_i9.AllVehiclesResponseEntity>
                  >(this, Invocation.method(#call, [])),
                ),
          )
          as _i4.Future<_i5.BaseResponse<_i9.AllVehiclesResponseEntity>>);
}
