// Mocks generated by Mockito 5.4.6 from annotations
// in tracking_app/test/auth/domain/usecase/forget_password_use_case_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:tracking_app/config/base/base_response.dart' as _i4;
import 'package:tracking_app/features/auth/domain/entities/forget_password_entity.dart'
    as _i5;
import 'package:tracking_app/features/auth/domain/entities/reset_password_entity.dart'
    as _i8;
import 'package:tracking_app/features/auth/domain/entities/verify_reset_code_entity.dart'
    as _i7;
import 'package:tracking_app/features/auth/domain/repositories/auth_repo.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [AuthRepo].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepo extends _i1.Mock implements _i2.AuthRepo {
  MockAuthRepo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.BaseResponse<_i5.ForgetPasswordEntity>> forgetPassword({
    required String? email,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#forgetPassword, [], {#email: email}),
            returnValue:
                _i3.Future<_i4.BaseResponse<_i5.ForgetPasswordEntity>>.value(
                  _i6.dummyValue<_i4.BaseResponse<_i5.ForgetPasswordEntity>>(
                    this,
                    Invocation.method(#forgetPassword, [], {#email: email}),
                  ),
                ),
          )
          as _i3.Future<_i4.BaseResponse<_i5.ForgetPasswordEntity>>);

  @override
  _i3.Future<_i4.BaseResponse<_i7.VerifyResetCodeEntity>> verifyResetCode({
    required String? resetCode,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#verifyResetCode, [], {#resetCode: resetCode}),
            returnValue:
                _i3.Future<_i4.BaseResponse<_i7.VerifyResetCodeEntity>>.value(
                  _i6.dummyValue<_i4.BaseResponse<_i7.VerifyResetCodeEntity>>(
                    this,
                    Invocation.method(#verifyResetCode, [], {
                      #resetCode: resetCode,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i4.BaseResponse<_i7.VerifyResetCodeEntity>>);

  @override
  _i3.Future<_i4.BaseResponse<_i8.ResetPasswordEntity>> resetPassword({
    required String? email,
    required String? newPassword,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#resetPassword, [], {
              #email: email,
              #newPassword: newPassword,
            }),
            returnValue:
                _i3.Future<_i4.BaseResponse<_i8.ResetPasswordEntity>>.value(
                  _i6.dummyValue<_i4.BaseResponse<_i8.ResetPasswordEntity>>(
                    this,
                    Invocation.method(#resetPassword, [], {
                      #email: email,
                      #newPassword: newPassword,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i4.BaseResponse<_i8.ResetPasswordEntity>>);
}
