// Mocks generated by Mockito 5.4.6 from annotations
// in tracking_app/test/features/profile/data/repositories/profile_repo_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:tracking_app/config/base/base_response.dart' as _i4;
import 'package:tracking_app/features/profile/data/datasources/profile_remote_data_source.dart'
    as _i2;
import 'package:tracking_app/features/profile/data/models/requests/reset_password_request_dto.dart'
    as _i9;
import 'package:tracking_app/features/profile/data/models/responses/all_vehicles_response_dto.dart'
    as _i7;
import 'package:tracking_app/features/profile/data/models/responses/profile_data_response_dto.dart'
    as _i5;
import 'package:tracking_app/features/profile/data/models/responses/reset_password_response_dto.dart'
    as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [ProfileRemoteDataSourceContract].
///
/// See the documentation for Mockito's code generation for more information.
class MockProfileRemoteDataSourceContract extends _i1.Mock
    implements _i2.ProfileRemoteDataSourceContract {
  MockProfileRemoteDataSourceContract() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.BaseResponse<_i5.ProfileDataResponseDto>> getProfileData() =>
      (super.noSuchMethod(
            Invocation.method(#getProfileData, []),
            returnValue:
                _i3.Future<_i4.BaseResponse<_i5.ProfileDataResponseDto>>.value(
                  _i6.dummyValue<_i4.BaseResponse<_i5.ProfileDataResponseDto>>(
                    this,
                    Invocation.method(#getProfileData, []),
                  ),
                ),
          )
          as _i3.Future<_i4.BaseResponse<_i5.ProfileDataResponseDto>>);

  @override
  _i3.Future<_i4.BaseResponse<_i7.AllVehiclesResponseDto>> getVehicles() =>
      (super.noSuchMethod(
            Invocation.method(#getVehicles, []),
            returnValue:
                _i3.Future<_i4.BaseResponse<_i7.AllVehiclesResponseDto>>.value(
                  _i6.dummyValue<_i4.BaseResponse<_i7.AllVehiclesResponseDto>>(
                    this,
                    Invocation.method(#getVehicles, []),
                  ),
                ),
          )
          as _i3.Future<_i4.BaseResponse<_i7.AllVehiclesResponseDto>>);

  @override
  _i3.Future<_i4.BaseResponse<_i8.ResetPasswordResponseDto>> resetPassword(
    _i9.ResetPasswordRequestDto? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#resetPassword, [request]),
            returnValue:
                _i3.Future<
                  _i4.BaseResponse<_i8.ResetPasswordResponseDto>
                >.value(
                  _i6.dummyValue<
                    _i4.BaseResponse<_i8.ResetPasswordResponseDto>
                  >(this, Invocation.method(#resetPassword, [request])),
                ),
          )
          as _i3.Future<_i4.BaseResponse<_i8.ResetPasswordResponseDto>>);
}
