// Mocks generated by Mockito 5.4.6 from annotations
// in tracking_app/test/features/auth/data/repositories/auth_repo_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dio/dio.dart' as _i13;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;
import 'package:tracking_app/config/base/base_response.dart' as _i5;
import 'package:tracking_app/core/network/model/user.dart' as _i6;
import 'package:tracking_app/core/network/model/user_entity.dart' as _i2;
import 'package:tracking_app/features/auth/data/datasources/auth_remote_data_source.dart'
    as _i3;
import 'package:tracking_app/features/auth/data/models/response/apply_now_response_dto.dart'
    as _i12;
import 'package:tracking_app/features/auth/data/models/response/driver_profile_response_dto.dart'
    as _i15;
import 'package:tracking_app/features/auth/data/models/response/forget_password_response.dart'
    as _i9;
import 'package:tracking_app/features/auth/data/models/response/reset_password_response.dart'
    as _i11;
import 'package:tracking_app/features/auth/data/models/response/vehicle_response_dto.dart'
    as _i14;
import 'package:tracking_app/features/auth/data/models/response/verify_reset_code_response.dart'
    as _i10;
import 'package:tracking_app/features/auth/domain/use_cases/login_params.dart'
    as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeUserEntity_0 extends _i1.SmartFake implements _i2.UserEntity {
  _FakeUserEntity_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AuthRemoteDataSourceContract].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRemoteDataSourceContract extends _i1.Mock
    implements _i3.AuthRemoteDataSourceContract {
  MockAuthRemoteDataSourceContract() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i5.BaseResponse<_i6.UserDto>> login(_i7.LoginParams? params) =>
      (super.noSuchMethod(
            Invocation.method(#login, [params]),
            returnValue: _i4.Future<_i5.BaseResponse<_i6.UserDto>>.value(
              _i8.dummyValue<_i5.BaseResponse<_i6.UserDto>>(
                this,
                Invocation.method(#login, [params]),
              ),
            ),
          )
          as _i4.Future<_i5.BaseResponse<_i6.UserDto>>);

  @override
  _i4.Future<_i5.BaseResponse<_i9.ForgetPasswordResponseDto>> forgetPassword({
    required String? email,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#forgetPassword, [], {#email: email}),
            returnValue:
                _i4.Future<
                  _i5.BaseResponse<_i9.ForgetPasswordResponseDto>
                >.value(
                  _i8.dummyValue<
                    _i5.BaseResponse<_i9.ForgetPasswordResponseDto>
                  >(
                    this,
                    Invocation.method(#forgetPassword, [], {#email: email}),
                  ),
                ),
          )
          as _i4.Future<_i5.BaseResponse<_i9.ForgetPasswordResponseDto>>);

  @override
  _i4.Future<_i5.BaseResponse<_i10.VerifyResetCodeResponseDto>>
  verifyResetCode({required String? resetCode}) =>
      (super.noSuchMethod(
            Invocation.method(#verifyResetCode, [], {#resetCode: resetCode}),
            returnValue:
                _i4.Future<
                  _i5.BaseResponse<_i10.VerifyResetCodeResponseDto>
                >.value(
                  _i8.dummyValue<
                    _i5.BaseResponse<_i10.VerifyResetCodeResponseDto>
                  >(
                    this,
                    Invocation.method(#verifyResetCode, [], {
                      #resetCode: resetCode,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i5.BaseResponse<_i10.VerifyResetCodeResponseDto>>);

  @override
  _i4.Future<_i5.BaseResponse<_i11.ResetPasswordResponseDto>> resetPassword({
    required String? email,
    required String? newPassword,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#resetPassword, [], {
              #email: email,
              #newPassword: newPassword,
            }),
            returnValue:
                _i4.Future<
                  _i5.BaseResponse<_i11.ResetPasswordResponseDto>
                >.value(
                  _i8.dummyValue<
                    _i5.BaseResponse<_i11.ResetPasswordResponseDto>
                  >(
                    this,
                    Invocation.method(#resetPassword, [], {
                      #email: email,
                      #newPassword: newPassword,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i5.BaseResponse<_i11.ResetPasswordResponseDto>>);

  @override
  _i4.Future<_i5.BaseResponse<_i12.ApplyNowResponseDto>> applyNow(
    _i13.FormData? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#applyNow, [request]),
            returnValue:
                _i4.Future<_i5.BaseResponse<_i12.ApplyNowResponseDto>>.value(
                  _i8.dummyValue<_i5.BaseResponse<_i12.ApplyNowResponseDto>>(
                    this,
                    Invocation.method(#applyNow, [request]),
                  ),
                ),
          )
          as _i4.Future<_i5.BaseResponse<_i12.ApplyNowResponseDto>>);

  @override
  _i4.Future<_i5.BaseResponse<_i14.VehicleResponseDto>> getVehicles() =>
      (super.noSuchMethod(
            Invocation.method(#getVehicles, []),
            returnValue:
                _i4.Future<_i5.BaseResponse<_i14.VehicleResponseDto>>.value(
                  _i8.dummyValue<_i5.BaseResponse<_i14.VehicleResponseDto>>(
                    this,
                    Invocation.method(#getVehicles, []),
                  ),
                ),
          )
          as _i4.Future<_i5.BaseResponse<_i14.VehicleResponseDto>>);

  @override
  _i4.Future<_i5.BaseResponse<_i15.DriverProfileResponseDto>>
  getDriverProfile() =>
      (super.noSuchMethod(
            Invocation.method(#getDriverProfile, []),
            returnValue:
                _i4.Future<
                  _i5.BaseResponse<_i15.DriverProfileResponseDto>
                >.value(
                  _i8.dummyValue<
                    _i5.BaseResponse<_i15.DriverProfileResponseDto>
                  >(this, Invocation.method(#getDriverProfile, [])),
                ),
          )
          as _i4.Future<_i5.BaseResponse<_i15.DriverProfileResponseDto>>);
}

/// A class which mocks [UserDto].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserDto extends _i1.Mock implements _i6.UserDto {
  MockUserDto() {
    _i1.throwOnMissingStub(this);
  }

  @override
  set firstName(String? value) => super.noSuchMethod(
    Invocation.setter(#firstName, value),
    returnValueForMissingStub: null,
  );

  @override
  set lastName(String? value) => super.noSuchMethod(
    Invocation.setter(#lastName, value),
    returnValueForMissingStub: null,
  );

  @override
  set email(String? value) => super.noSuchMethod(
    Invocation.setter(#email, value),
    returnValueForMissingStub: null,
  );

  @override
  set gender(String? value) => super.noSuchMethod(
    Invocation.setter(#gender, value),
    returnValueForMissingStub: null,
  );

  @override
  set phone(String? value) => super.noSuchMethod(
    Invocation.setter(#phone, value),
    returnValueForMissingStub: null,
  );

  @override
  set photo(String? value) => super.noSuchMethod(
    Invocation.setter(#photo, value),
    returnValueForMissingStub: null,
  );

  @override
  set role(String? value) => super.noSuchMethod(
    Invocation.setter(#role, value),
    returnValueForMissingStub: null,
  );

  @override
  set wishlist(List<dynamic>? value) => super.noSuchMethod(
    Invocation.setter(#wishlist, value),
    returnValueForMissingStub: null,
  );

  @override
  set id(String? value) => super.noSuchMethod(
    Invocation.setter(#id, value),
    returnValueForMissingStub: null,
  );

  @override
  set addresses(List<dynamic>? value) => super.noSuchMethod(
    Invocation.setter(#addresses, value),
    returnValueForMissingStub: null,
  );

  @override
  set createdAt(DateTime? value) => super.noSuchMethod(
    Invocation.setter(#createdAt, value),
    returnValueForMissingStub: null,
  );

  @override
  Map<String, dynamic> toJson() =>
      (super.noSuchMethod(
            Invocation.method(#toJson, []),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  _i2.UserEntity toDomain() =>
      (super.noSuchMethod(
            Invocation.method(#toDomain, []),
            returnValue: _FakeUserEntity_0(
              this,
              Invocation.method(#toDomain, []),
            ),
          )
          as _i2.UserEntity);
}
