// Mocks generated by Mockito 5.4.6 from annotations
// in tracking_app/test/features/oreder_details/domain/use_cases/watch_order_state_use_case_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:tracking_app/config/base/base_response.dart' as _i4;
import 'package:tracking_app/features/oreder_details/domain/entities/order_details_response_entity.dart'
    as _i5;
import 'package:tracking_app/features/oreder_details/domain/entities/update_order_state_params.dart'
    as _i8;
import 'package:tracking_app/features/oreder_details/domain/entities/update_order_state_response_entity.dart'
    as _i7;
import 'package:tracking_app/features/oreder_details/domain/repositories/order_details_repo.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [OrderDetailsRepo].
///
/// See the documentation for Mockito's code generation for more information.
class MockOrderDetailsRepo extends _i1.Mock implements _i2.OrderDetailsRepo {
  MockOrderDetailsRepo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.BaseResponse<_i5.OrdersResponseEntity>>
  getAllPendingOrders() =>
      (super.noSuchMethod(
            Invocation.method(#getAllPendingOrders, []),
            returnValue:
                _i3.Future<_i4.BaseResponse<_i5.OrdersResponseEntity>>.value(
                  _i6.dummyValue<_i4.BaseResponse<_i5.OrdersResponseEntity>>(
                    this,
                    Invocation.method(#getAllPendingOrders, []),
                  ),
                ),
          )
          as _i3.Future<_i4.BaseResponse<_i5.OrdersResponseEntity>>);

  @override
  _i3.Future<_i4.BaseResponse<_i7.UpdateOrderStateResponseEntity>>
  updateOrderState(_i8.UpdateOrderStateParams? params) =>
      (super.noSuchMethod(
            Invocation.method(#updateOrderState, [params]),
            returnValue:
                _i3.Future<
                  _i4.BaseResponse<_i7.UpdateOrderStateResponseEntity>
                >.value(
                  _i6.dummyValue<
                    _i4.BaseResponse<_i7.UpdateOrderStateResponseEntity>
                  >(this, Invocation.method(#updateOrderState, [params])),
                ),
          )
          as _i3.Future<_i4.BaseResponse<_i7.UpdateOrderStateResponseEntity>>);

  @override
  _i3.Future<void> saveCurrentOrder({
    required String? driverId,
    required String? orderId,
    required String? state,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#saveCurrentOrder, [], {
              #driverId: driverId,
              #orderId: orderId,
              #state: state,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteCurrentOrder({required String? driverId}) =>
      (super.noSuchMethod(
            Invocation.method(#deleteCurrentOrder, [], {#driverId: driverId}),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Stream<String?> watchOrderState({required String? driverId}) =>
      (super.noSuchMethod(
            Invocation.method(#watchOrderState, [], {#driverId: driverId}),
            returnValue: _i3.Stream<String?>.empty(),
          )
          as _i3.Stream<String?>);
}
