// Mocks generated by Mockito 5.4.6 from annotations
// in tracking_app/test/features/profile/api/datasources/profile_remote_data_source_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:mockito/mockito.dart' as _i1;
import 'package:tracking_app/features/profile/api/api_client/profile_api_client.dart'
    as _i5;
import 'package:tracking_app/features/profile/data/models/responses/all_vehicles_response_dto.dart'
    as _i2;
import 'package:tracking_app/features/profile/data/models/responses/profile_data_response_dto.dart'
    as _i4;
import 'package:tracking_app/features/profile/data/models/responses/single_vehicle_response_dto.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeAllVehiclesResponseDto_0 extends _i1.SmartFake
    implements _i2.AllVehiclesResponseDto {
  _FakeAllVehiclesResponseDto_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSingleVehicleResponseDto_1 extends _i1.SmartFake
    implements _i3.SingleVehicleResponseDto {
  _FakeSingleVehicleResponseDto_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeProfileDataResponseDto_2 extends _i1.SmartFake
    implements _i4.ProfileDataResponseDto {
  _FakeProfileDataResponseDto_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ProfileApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockProfileApiClient extends _i1.Mock implements _i5.ProfileApiClient {
  MockProfileApiClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i2.AllVehiclesResponseDto> getVehicles() =>
      (super.noSuchMethod(
            Invocation.method(#getVehicles, []),
            returnValue: _i6.Future<_i2.AllVehiclesResponseDto>.value(
              _FakeAllVehiclesResponseDto_0(
                this,
                Invocation.method(#getVehicles, []),
              ),
            ),
          )
          as _i6.Future<_i2.AllVehiclesResponseDto>);

  @override
  _i6.Future<_i3.SingleVehicleResponseDto> getVehicleById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getVehicleById, [id]),
            returnValue: _i6.Future<_i3.SingleVehicleResponseDto>.value(
              _FakeSingleVehicleResponseDto_1(
                this,
                Invocation.method(#getVehicleById, [id]),
              ),
            ),
          )
          as _i6.Future<_i3.SingleVehicleResponseDto>);

  @override
  _i6.Future<_i4.ProfileDataResponseDto> getProfileData() =>
      (super.noSuchMethod(
            Invocation.method(#getProfileData, []),
            returnValue: _i6.Future<_i4.ProfileDataResponseDto>.value(
              _FakeProfileDataResponseDto_2(
                this,
                Invocation.method(#getProfileData, []),
              ),
            ),
          )
          as _i6.Future<_i4.ProfileDataResponseDto>);
}
