// Mocks generated by Mockito 5.4.6 from annotations
// in tracking_app/test/features/profile/api/datasources/profile_remote_data_source_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;
import 'dart:io' as _i11;

import 'package:dio/dio.dart' as _i12;
import 'package:mockito/mockito.dart' as _i1;
import 'package:tracking_app/features/profile/api/api_client/profile_api_client.dart'
    as _i7;
import 'package:tracking_app/features/profile/data/models/edit_profile_request.dart'
    as _i10;
import 'package:tracking_app/features/profile/data/models/requests/reset_password_request_dto.dart'
    as _i9;
import 'package:tracking_app/features/profile/data/models/responses/all_vehicles_response_dto.dart'
    as _i2;
import 'package:tracking_app/features/profile/data/models/responses/profile_data_response_dto.dart'
    as _i4;
import 'package:tracking_app/features/profile/data/models/responses/reset_password_response_dto.dart'
    as _i5;
import 'package:tracking_app/features/profile/data/models/responses/single_vehicle_response_dto.dart'
    as _i3;
import 'package:tracking_app/features/profile/data/models/responses/update_vehicle_response_dto.dart'
    as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeAllVehiclesResponseDto_0 extends _i1.SmartFake
    implements _i2.AllVehiclesResponseDto {
  _FakeAllVehiclesResponseDto_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSingleVehicleResponseDto_1 extends _i1.SmartFake
    implements _i3.SingleVehicleResponseDto {
  _FakeSingleVehicleResponseDto_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeProfileDataResponseDto_2 extends _i1.SmartFake
    implements _i4.ProfileDataResponseDto {
  _FakeProfileDataResponseDto_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeResetPasswordResponseDto_3 extends _i1.SmartFake
    implements _i5.ResetPasswordResponseDto {
  _FakeResetPasswordResponseDto_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUpdateVehicleResponseDto_4 extends _i1.SmartFake
    implements _i6.UpdateVehicleResponseDto {
  _FakeUpdateVehicleResponseDto_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ProfileApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockProfileApiClient extends _i1.Mock implements _i7.ProfileApiClient {
  MockProfileApiClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<_i2.AllVehiclesResponseDto> getVehicles() =>
      (super.noSuchMethod(
            Invocation.method(#getVehicles, []),
            returnValue: _i8.Future<_i2.AllVehiclesResponseDto>.value(
              _FakeAllVehiclesResponseDto_0(
                this,
                Invocation.method(#getVehicles, []),
              ),
            ),
          )
          as _i8.Future<_i2.AllVehiclesResponseDto>);

  @override
  _i8.Future<_i3.SingleVehicleResponseDto> getVehicleById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getVehicleById, [id]),
            returnValue: _i8.Future<_i3.SingleVehicleResponseDto>.value(
              _FakeSingleVehicleResponseDto_1(
                this,
                Invocation.method(#getVehicleById, [id]),
              ),
            ),
          )
          as _i8.Future<_i3.SingleVehicleResponseDto>);

  @override
  _i8.Future<_i4.ProfileDataResponseDto> getProfileData() =>
      (super.noSuchMethod(
            Invocation.method(#getProfileData, []),
            returnValue: _i8.Future<_i4.ProfileDataResponseDto>.value(
              _FakeProfileDataResponseDto_2(
                this,
                Invocation.method(#getProfileData, []),
              ),
            ),
          )
          as _i8.Future<_i4.ProfileDataResponseDto>);

  @override
  _i8.Future<_i5.ResetPasswordResponseDto> resetPassword(
    _i9.ResetPasswordRequestDto? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#resetPassword, [request]),
            returnValue: _i8.Future<_i5.ResetPasswordResponseDto>.value(
              _FakeResetPasswordResponseDto_3(
                this,
                Invocation.method(#resetPassword, [request]),
              ),
            ),
          )
          as _i8.Future<_i5.ResetPasswordResponseDto>);

  @override
  _i8.Future<_i4.ProfileDataResponseDto> editProfile(
    _i10.EditProfileJsonRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#editProfile, [request]),
            returnValue: _i8.Future<_i4.ProfileDataResponseDto>.value(
              _FakeProfileDataResponseDto_2(
                this,
                Invocation.method(#editProfile, [request]),
              ),
            ),
          )
          as _i8.Future<_i4.ProfileDataResponseDto>);

  @override
  _i8.Future<void> uploadPhoto(_i11.File? photo) =>
      (super.noSuchMethod(
            Invocation.method(#uploadPhoto, [photo]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<_i6.UpdateVehicleResponseDto> updateVehicleInfo(
    _i12.FormData? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateVehicleInfo, [request]),
            returnValue: _i8.Future<_i6.UpdateVehicleResponseDto>.value(
              _FakeUpdateVehicleResponseDto_4(
                this,
                Invocation.method(#updateVehicleInfo, [request]),
              ),
            ),
          )
          as _i8.Future<_i6.UpdateVehicleResponseDto>);
}
