// Mocks generated by Mockito 5.4.6 from annotations
// in tracking_app/test/features/oreder_details/presentation/cubit/order_details_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;
import 'package:tracking_app/config/base/base_response.dart' as _i5;
import 'package:tracking_app/features/oreder_details/domain/entities/update_order_state_params.dart'
    as _i7;
import 'package:tracking_app/features/oreder_details/domain/entities/update_order_state_response_entity.dart'
    as _i6;
import 'package:tracking_app/features/oreder_details/domain/repositories/order_details_repo.dart'
    as _i2;
import 'package:tracking_app/features/oreder_details/domain/use_cases/save_current_order_usecase.dart'
    as _i9;
import 'package:tracking_app/features/oreder_details/domain/use_cases/update_order_state_usecase.dart'
    as _i3;
import 'package:tracking_app/features/oreder_details/domain/use_cases/watch_order_state_usecase.dart'
    as _i10;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeOrderDetailsRepo_0 extends _i1.SmartFake
    implements _i2.OrderDetailsRepo {
  _FakeOrderDetailsRepo_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [UpdateOrderStateUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockUpdateOrderStateUseCase extends _i1.Mock
    implements _i3.UpdateOrderStateUseCase {
  MockUpdateOrderStateUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.OrderDetailsRepo get repo =>
      (super.noSuchMethod(
            Invocation.getter(#repo),
            returnValue: _FakeOrderDetailsRepo_0(
              this,
              Invocation.getter(#repo),
            ),
          )
          as _i2.OrderDetailsRepo);

  @override
  _i4.Future<_i5.BaseResponse<_i6.UpdateOrderStateResponseEntity>> call(
    _i7.UpdateOrderStateParams? params,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue:
                _i4.Future<
                  _i5.BaseResponse<_i6.UpdateOrderStateResponseEntity>
                >.value(
                  _i8.dummyValue<
                    _i5.BaseResponse<_i6.UpdateOrderStateResponseEntity>
                  >(this, Invocation.method(#call, [params])),
                ),
          )
          as _i4.Future<_i5.BaseResponse<_i6.UpdateOrderStateResponseEntity>>);
}

/// A class which mocks [SaveCurrentOrderUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockSaveCurrentOrderUseCase extends _i1.Mock
    implements _i9.SaveCurrentOrderUseCase {
  MockSaveCurrentOrderUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.OrderDetailsRepo get repo =>
      (super.noSuchMethod(
            Invocation.getter(#repo),
            returnValue: _FakeOrderDetailsRepo_0(
              this,
              Invocation.getter(#repo),
            ),
          )
          as _i2.OrderDetailsRepo);

  @override
  _i4.Future<void> call({
    required String? driverId,
    required String? orderId,
    required String? state,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {
              #driverId: driverId,
              #orderId: orderId,
              #state: state,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [WatchOrderStateUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockWatchOrderStateUseCase extends _i1.Mock
    implements _i10.WatchOrderStateUseCase {
  MockWatchOrderStateUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.OrderDetailsRepo get repo =>
      (super.noSuchMethod(
            Invocation.getter(#repo),
            returnValue: _FakeOrderDetailsRepo_0(
              this,
              Invocation.getter(#repo),
            ),
          )
          as _i2.OrderDetailsRepo);

  @override
  _i4.Stream<String?> call({required String? driverId}) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {#driverId: driverId}),
            returnValue: _i4.Stream<String?>.empty(),
          )
          as _i4.Stream<String?>);
}
