// Mocks generated by Mockito 5.4.6 from annotations
// in tracking_app/test/features/auth/presentation/login/cubit/login_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;
import 'package:tracking_app/config/base/base_response.dart' as _i5;
import 'package:tracking_app/core/network/model/user_entity.dart' as _i6;
import 'package:tracking_app/features/auth/domain/repositories/auth_repo.dart'
    as _i2;
import 'package:tracking_app/features/auth/domain/use_cases/login_params.dart'
    as _i7;
import 'package:tracking_app/features/auth/domain/use_cases/login_use_case.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeAuthRepo_0 extends _i1.SmartFake implements _i2.AuthRepo {
  _FakeAuthRepo_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [LoginUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockLoginUseCase extends _i1.Mock implements _i3.LoginUseCase {
  MockLoginUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AuthRepo get authRepo =>
      (super.noSuchMethod(
            Invocation.getter(#authRepo),
            returnValue: _FakeAuthRepo_0(this, Invocation.getter(#authRepo)),
          )
          as _i2.AuthRepo);

  @override
  _i4.Future<_i5.BaseResponse<_i6.UserEntity>> call(_i7.LoginParams? params) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue: _i4.Future<_i5.BaseResponse<_i6.UserEntity>>.value(
              _i8.dummyValue<_i5.BaseResponse<_i6.UserEntity>>(
                this,
                Invocation.method(#call, [params]),
              ),
            ),
          )
          as _i4.Future<_i5.BaseResponse<_i6.UserEntity>>);
}
